scr/app.py
from flask import Flask, render_template

from scr.common.database import Database




app = Flask(__name__)
app.config.from_object('config')

app.secret_key ='123'


@app.before_first_request
def init_db():
    Database.initialize()


@app.route('/')
def home():
    return render_template('home.html')

from scr.models.users.views import user_buleprint
from scr.models.alerts.views import alert_blueprint
from scr.models.stores.views import store_buleprint
# register the blue[print with prefix users
app.register_blueprint(user_buleprint, url_prefix = '/users')
app.register_blueprint(store_buleprint, url_prefix = '/stores')
app.register_blueprint(alert_blueprint, url_prefix = '/alerts')

scr/models/alerts/views.py
from flask import Blueprint, render_template, request, session, url_for, redirect

from scr.models.alerts.alert import Alert
from scr.models.items.item import Item

alert_blueprint = Blueprint('alerts', __name__)

@alert_blueprint.route('/')
def index():
    return "This is the alerts index"

@alert_blueprint.route('/new', methods=['GET', 'POST'])
def create_alert():
    if request.method == 'POST':
        name=request.form['name']
        url = request.form['url']
        price_limit =request.form['price_limit']

        item = Item(name, url)
        item.save_to_mongo()

        alert= Alert(session['email'], price_limit, item._id)
        alert.load_item_price() # already save to db

    return render_template('alerts/new_alert.html')



@alert_blueprint.route('/deactivate/alert_id' )
def deactivate_alert(alert_id):
    Alert.find_by_id(alert_id).deactivate()
    return redirect(url_for('users.user_alerts'))

@alert_blueprint.route('/activate/alert_id' )
def activate_alert(alert_id):
    Alert.find_by_id(alert_id).activate()
    return redirect(url_for('users.user_alerts'))

@alert_blueprint.route('/alert/<string:alert_id>')
def get_alert_page(alert_id):
    alert = Alert.find_by_id(alert_id)
    return render_template('alerts/alert.html')



@alert_blueprint.route('/for_user/<string:user_id>')
def get_alerts_for_user(user_id):
    pass


@alert_blueprint.route('/check_price/<string:alert_id>')
def check_alert_price(alert_id):
    Alert.find_by_id(alert_id).load_item_price()
    return redirect(url_for('.get_alert_page', alert_id=alert_id))

scr/models/items/views.py
from flask import Blueprint

item_blueprint = Blueprint('items', __name__)

@item_blueprint.route('/item/<string:name>')
def item_page(name):
    pass


@item_blueprint.route('/load')
def load_item():
    # load on item data using their store and return a Json representation of it
    pass

scr/models/stores/views.py
import json

from flask import Blueprint, render_template, request, redirect, url_for

from scr.models.stores.store import Store

store_buleprint =Blueprint('stores', __name__)

@store_buleprint.route('/')
def index():
    stores=Store.all()
    return render_template('stores/store_index.html', stores=stores)

@store_buleprint.route('/store/<string:store_id>')
def store_page(store_id):
    return render_template('stores/store.html', store=Store.get_by_id(store_id))


@store_buleprint.route('/edit/<string:store_id>', methods=['GET', 'POST'])
def edit_store(sotre_id):
    if request.method =='POST':
        pass
    return

@store_buleprint.route('/delete/<string:store_id>')
def delete_store():
    return


@store_buleprint.route('/new', methods=['GET', 'POST'])
def create_store():
    if request.method=='POST':
        name=request.form['name']
        url_prefix=request.form['url_prefix']
        tag_name=request.form['tag_name']
        query=json.loads(request.form['query'])

        Store(name, url_prefix, tag_name, query).save_to_mongo()

        return redirect(url_for('.index'))

    return render_template('stores/new_store.html')

scr/models/users/views.py
from flask import Blueprint, request, session, url_for, render_template
from werkzeug.utils import redirect

from scr.models.alerts.alert import Alert
from scr.models.users.user import User
import scr.models.users.errors as UserErrors



user_buleprint = Blueprint('user', __name__)



@user_buleprint.route('/login', methods =['GET', 'POST'])
def login_user():
    if request.method == 'POST':
        # check login is valid
        email =request.form['email']
        password = request.form['password']

        try:
            if User.is_login_valid(email, password):
                session['email']=email
                return redirect(url_for('.user_alerts'))
        except UserErrors.UserError as e:
            return e.message

    return render_template('/users/login.html')




@user_buleprint.route('/register')
def register_user():
    if request.method == 'POST':
        # check login is valid
        email =request.form['email']
        password = request.form['password']

        try:
            if User.register_user(email, password):
                session['email']=email
                return redirect(url_for('.user_alerts'))
        except UserErrors.UserError as e:
            return e.message

    return render_template('/users/register.html')



@user_buleprint.route('/alerts')
def user_alerts():
    user = User.find_by_email(session['email'])
    alerts = user.get_alert()
    return render_template('users/alerts/jinja2', alerts = alerts)

@user_buleprint.route('/logout')
def logout_user():
    session['email'] = None
    return redirect(url_for('home'))

@user_buleprint.route('/check_alerts/<string:user_id>')
def check_user_alerts(user_id):
    pass

scr/templates/alerts/alert.html
{% extends "base.html" %}
{% block content %}
    <div class="page-header">
        <h1>Alert<small>for '{{ alert.item.name }}'</small></h1>
    </div>
    <p>Last price found</p>
    <p>Last price found <strong>{{ alert.item.price }}</strong></p>
    <p>Last checked on <strong>{{ alert.last_checked.strftime("%d-%m-%Y at %H:%M") }}</strong></p>

    <div class="panel panel-default">
        <div class="panel-body">
            <a class="btn btn-default" href="{{ alert.item.url }}" role="button">Visit Site</a>
            {% if alert.active %}
                <a class="btn btn-danger" href="{{ url_for('alerts.deacivate_alert', alert_id = alert._id)}}" role="button">Deactive Alert</a>
            {% else %}
                <a class="btn btn-success" href="{{ url_for('alerts.acivate_alert', alert_id = alert._id)}}" role="button">Active Alert</a>
            {% endif %}

            <a class="btn btn-warning" href="{{ url_for('alerts.check_alert_price', alert_id = alert._id)}}" role="button">Check Alert Price</a>
        </div>
    </div>
{% endblock %}

scr/templates/alerts/create_alert.html
{% extends "base.html" %}
{% block content %}

{% endblock %}

scr/templates/alerts/edit_alert.html
{% extends "base.html" %}
{% block content %}
    
{% endblock %}

scr/templates/alerts/new_alert.html
<{% extends "base.html" %}
{% block content %}
    <div class="page-header">
        <h1>Create Alert</h1>
    </div>
    <div class="form-size">
        <form method="post">
            <div class="form-group">
                <label for="name">Alert/Item Name</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="Name">
            </div>
            <div class="form-group">
                <label for="url">URL</label>
                <input type="text" class="form-control" id="url" name="url" placeholder="Url">
            </div>
            <div class="form-group">
                <label for="price_limit">Alert Limit</label>
                <input type="text" class="form-control" id="price_limit" name="price_limit" placeholder="45.0" aria-describedby="priceLimitBlock">
                <p id="priceLimitBlock" class="help-block">We will send you an email when price reaches or goes under this</p>
            </div>
            <button type="submit" class="btn btn-default">Create</button>

        </form>
    </div>
    <a class="btn btn-success" href="{{ url_for('alerts.create_alert')}}">Create new</a>
{% endblock %}

scr/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pricing Service</title>

    {% include 'html_dependencies.html' %}

</head>
<body>

<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
             <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
             </button>

            <a class="navbar-brand" href="/" title="Home">Pricing</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">

                <li><a href="{{ url_for('stores.index')}}">Stores</a></li>
                <li><a href="{{ url_for('alerts.index')}}">Alerts</a></li>
            </ul>
            {% if session['email'] %}
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{{ url_for('users.user_alerts')}}">Your Alerts</a></li>
                    <li><a href="{{ url_for('users.logout_user')}}">Log out</a></li>

                </ul>
            {% else %}
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{{ url_for('users.register_user')}}">Sign up</a></li>
                    <li><a href="{{ url_for('users.login_user')}}">Log in</a></li>

                </ul>
            {% endif %}

        </div>

    </div>
</nav>

<div class="content container">
    {% block content %}


    {% endblock %}
</div>

</body>
</html>

scr/templates/home.html
{% extends."base.html" %}
{% block content %}
<p>Hello, world!</p>
{% endblock %}

scr/templates/html_dependencies.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrp/3.3.6/css/bootstrap.min.css">
<link rel="stylesheet" href ="{{ url_for('static', filename='css/style.css')}}">
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<link rel= "stylesheet" href ="{{ url_for('static', filename='css/style.css') }}">

scr/templates/stores/create_store.html
{% extends "base.html" %}
{% block content %}
    
{% endblock %}

scr/templates/stores/edit_store.html
{% extends "base.html" %}
{% block content %}
    
{% endblock %}

scr/templates/stores/new_store.html
{% extends "base.html" %}
{% block content %}
    <div class="page-header">
        <h1>Create Store</h1>
    </div>
    <div class="form-size">
        <form method="post">
            <div class="form-group">
                <label for="name">Store name</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="Store Name">
            </div>
             <div class="form-group">
                <label for="url_prefix">Store URL Prefix</label>
                <input type="text" class="form-control" id="url_prefix" name="url_prefix" placeholder="http://..." aria-describedby="storeURLPrefixHelp">
                <span id="storeURLPrefixHelp" class="help-block">What characters do URLs of all items in this online store start with?</span>
            </div>
            <div class="form-group">
                <label for="tag_name">Tag Name</label>
                <input type="text" class="form-control" id="tag_name" name="tag_name" placeholder="span" value="span" aria-describedby="storeTagNameHelp">
                <span id="storeTagNameHelp" class="help-block">What is the HTML tag of the item that contains the item price?</span>
            </div>
            <div class="form-group">
                <label for="query">Tag Name</label>
                <input type="text" class="form-control" id="query" name="query" placeholder='{{"id":"price-now"}}' value='{{"id":"price-now"}}'  aria-describedby="queryHelpBlock">
                <span id="queryHelpBlock" class="help-block">What Json query would we have to do to find the specific tag with the price?</span>
            </div>
            <button type="button" class="btn btn-default">Create</button>
        </form>
    </div>

{% endblock %}

scr/templates/stores/store.html
{% extends "base.html" %}
{% block content %}
    <div class="page-header">
        <h1>Store <small>{{ store.name}}</small></h1>
    </div>
    <p>All URLs in this store should be start with <strong>{{ store.url_perfix }}</strong></p>
    <div class="panel panel-default">
        <div class="panel-body">
            <a class="btn btn-warning" href="{{ url_for('store.edit_store', store_id=store._id)}}" role="button">Edit Store</a>
            <a class="btn btn-danger" href="{{ url_for('stores.delete_store', store_id=store._id}}" role="button">Permanently Delete Store</a>

        </div>
    </div>
{% endblock %}

scr/templates/stores/store_index.html
<{% extends "base.html" %}
{% block content %}
    <div class="page-header">
        <h1>Stores<small>list of stores</small></h1>
    </div>
    <div class="list-group">
        {% for store in stores %}
            Display list of stores here as
            <a href="{{ url_for('stores.store_page', store_id=store._id) }}" class='list-group-item'>
            <h4 class='list-group-item-title'>Title</h4>
                <p class='list-group-item-text'>All URLs in this store should start with <strong>{{ store.url_perfix }}</strong></p></a>

        {% endfor %}
    </div>
    <a class="btn btn-success" href="{{ url_for('stores.create_store')}}">
        <span class="glyphicon glyphicon-plus"></span> Create new
    </a>
{% endblock %}

scr/templates/stores/store_list.html
{% extends "base.html" %}
{% block content %}
    
{% endblock %}

scr/templates/users/alerts.html
{% extends "base.html" %}
{% block content %}
    <div class="page-header">
        <h1>Alert</h1>
    </div>
    <div class="list-group">
        {% for alert in alerts %}
            <a href="{{ url_for('alerts.get_alert_page',  alert_id = alert_id )}}" class="list-group-item">
                <h4 class="list-group-item-heading">Alert for{{ alert.item.name }}</h4>
                <p class="list-group-item-text">Last price found <strong>{{ alert.item.price }}</strong><br/>
                Last checked on <strong>{{ alert.last_checked.strftime("%d-%m-%Y at %H:%M") }}</strong></p>
            </a>
        {% endfor %}
    </div>
    <a class="btn btn-success" href="{{ url_for('alerts.create_alert')}}">Create new</a>
{% endblock %}

scr/templates/users/login.html
{% extends "base.html" %}
{% block content %}
    <div class="form-size">
        <form action="{{ url_for('users.login_user')}}" method="post">
            <div class="form-group">
                <label for="email">Email address</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="Email" >
            </div>
            <div class="form-group">
                <label form="password">Password</label>
                <input type="password" class="form-control" id="password" name="password" placeholder="Password" >
            </div>
            <button type="'submit" class="btn btn-success">Log in</button>
        </form>
    </div>
{% endblock %}

scr/templates/users/register.html
{% extends "base.html" %}
{% block content %}
    <div class="form-size">
        <form action="{{ url_for('users.register_user')}}" method="post">
            <div class="form-group">
                <label for="email">Email address</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="Email" >
            </div>
            <div class="form-group">
                <label form="password">Password</label>
                <input type="password" class="form-control" id="epasswordmail" name="password" placeholder="Password" >
            </div>
            <button type="'submit" class="btn btn-success">Sign up</button>
        </form>
    </div>
{% endblock %}